name: amf3-radar-examples-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python<=3.11
  - matplotlib
  - jupyterlab
  - cartopy
  - numpy
  - dask
  - distributed
  - xarray
  - pandas
  - geopandas
  - fiona
  - cfgrib
  - pip
  - pip:
    - -r doc-requirements.txt
    - arm_pyart
    - act-atmos
